first pass at %add-column
uqbar-dao/nectar pull request #1
Opened 2023-03-19 22:33 UTC by litlep-nibbyt

My first attempt at adding the `%add-column` query. There are some things that I am unsure of so I am posting what I have so far to make sure I'm on the right track.

The %add-column query is  `['%add-column table=@ col-name=@ =column-type]`. 

Inside of `db`, I added a gate for add-column which then calls the corresponding `+add-column` arm inside of `tab`.

`~(add-column tab table)` does three things
1. Adds the `column-type` to the schema (but does not validate that they are valid)
2. Inserts nulls at the end of each row. The implicit assumption is that the new column is going to be in the last `spot`. 
3. Calls `~(insert tab table)` to add the zero-concated rows to the table.

How I've been using it:

1. Import this core under the name of `nec-box`:

```hoon
|%
++  variable-length-db
  |=  n-rows=@ud
  |^  
  ^-  database 
  =/  deebee=database  empty-database
  %+  ~(insert-rows db deebee) 
    %myapp^%boards  (create-rows n-rows)
  
  ++  create-rows
    |=  n=@ud
    ^-  (list row)
    =/  c  1
    =/  rows=(list row)  ~[`row`~[id=0 name='0']]
    |-
    ?:  =(c n)
      rows
    %=  $
      c   +(c)
      rows  (weld rows ~[`row`~[id=c name=(crip "{<c>}")]])
    ==
  ++  empty-database
    %+  ~(add-table db *database)
      %myapp^%boards
    ^-  table
    :^    (make-schema ~[[%id [0 %.n %ud]] [%name [1 %.n %t]]])
        primary-key=~[%id]
      (make-indices ~[[~[%id] primary=& autoincrement=~ unique=& clustered=|]])
    ~
  --
--
```

2. Run the following dojo commands
```
> =db (variable-length-db:necbox 10)
> (run-mutation:nec-box db [%add-column %boards %nu [2 %.n %ud]])

2023-03-20 16:17 UTC, dr-frmr requested changes

2023-03-20 16:17 UTC, dr-frmr commented on lib/nectar.hoon
> +    ~|  "Primary key must also be a unique index."
would prefer error message here of `"%nectar: primary key must also be a unique index"`

2023-03-20 16:17 UTC, dr-frmr commented on lib/nectar.hoon
> +      `^row`(welp row ~[0])
rather than just append the column to end of every row, we need to use the `spot` value in `column-type` to show what index in row-list the column should be stuck into.

in order to make this work, it's also important to go through the existing columns in `schema.table` and check if the new column's `spot` is already taken, in which case, the existing column in that `spot` and all columns that come after it should have their `spot` incremented by 1.

2023-03-20 16:17 UTC, dr-frmr commented on sur/nectar.hoon
> +      [%add-column table=@ col-name=@ =column-type]
this is great, do you want to go ahead and write the logic for drop-column and edit-column too? i believe all 3 operations will share a lot of code, particularly in the `db` door, they can probably all be handled in a bundle there and just have a switch-statement that calls separate arms in the `tab` door.

2023-03-22 01:30 UTC, litlep-nibbyt commented on sur/nectar.hoon
> +      [%add-column table=@ col-name=@ =column-type]
I will add drop and edit in a separate PR

2023-03-22 01:38 UTC, litlep-nibbyt commented
@dr-frmr I've made it so that the new column can be inserted at any `spot` rather than only `(#spots + 1)`. `+add-column` now checks if the spot is taken and shifts all columns that come after the requested spot to the right if it is. 

I also added an additional argument `fill` to the sample  in case the user wants to initialize the column to a value other than 0.

I tested this by importing the same core as [above](https://github.com/uqbar-dao/nectar/pull/1#issue-1631143486) under the name `nec-box` and running:

```
> =db (variable-length-db:nec-box 10)
> db
> (run-mutation:nec-box db [%add-column %boards %nu [0 %.n %ud] 42])
> (run-mutation:nec-box db [%add-column %boards %nu [1 %.n %ud] 42])
```
comparing `db` with the results of the two queries. Perhaps I can move this over to a unit test?

2023-03-22 21:50 UTC, dr-frmr approved these changes
LGTM. If you want to add unit tests go ahead, but I don't have any so I wouldn't expect or require it for new features -- probably in the future though

2023-03-23 21:02 UTC, merged